@url = http://localhost:5162
@docker_url = http://localhost:8080
@aca_url = https://demo-container-app.delightfulplant-c018886b.australiaeast.azurecontainerapps.io

### View OpenApi doc
GET {{url}}/openapi/v1.json
Accept: application/json
###


### Test endpionts

GET {{aca_url}}/demo/cosmosdb
###

GET {{aca_url}}/demo/eventgrid
###

GET {{aca_url}}/demo/blobstorage
###
